### ISSUE TITLE
MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by geraldapeoples** [diyao/xlsx-json-js#1]
I installed using npm.

I added the correct import statement to the script but when I ran it I got the MODULE_NOT_FOUND error.

I modified the "package.json" file manually for the package -

Changed -

"main": "dist/xlsx-json-js.cjs.js",
  "module": "dist/xlsx-json-js.esm.js",

To -

"main": "dist/xlsx-json-js.cjs.min.js",
  "module": "dist/xlsx-json-js.esm.min.js",

And it worked after that.

**Comment by diyao** [comment]
@geraldapeoples 
Thank you for your reminder!

Sorry to trouble you, this error has been fixed.

**Comment by geraldapeoples** [comment]
@diyao 
No problem, thank you for the brilliant package!
